# fly.toml app configuration file generated for recipebook-backend on 2023-05-22T19:00:29+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "recipebook-backend"
primary_region = "otp"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  source="upload"
  destination="/upload"
